config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :languages
end

app/models/language.rb
class Language < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    @language = Language.new
    @languages = Language.all
  end

  def create
    @language = Language.create(language_params)
    if @language.save
      redirect_to languages_path
    else
      render :index
    end
  end

  def show
    @language = Language.find(params[:id])
  end

  def edit
    @language = Language.find(params[:id])
  end

  def update
    @language = Language.find(params[:id])
    @language.update_attributes!(language_params)

    redirect_to languages_path
  end

  def destroy
    @language = Language.find(params[:id]).delete

    redirect_to languages_path
  end

  private
  def language_params
    params.require(:language).permit(:name_of_language, :country_spoken)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/languages/edit.html.erb
<%= form_for @language do |f| %>
  <p>
    <%= f.label :name_of_language %>
    <%= f.text_field :name_of_language %>
  </p>
  <p>
    <%= f.label :country_spoken %>
    <%= f.text_field :country_spoken %>
  </p>
  <p>
    <%= f.submit 'Update language' %>
  </p>
<% end %>

app/views/languages/index.html.erb
<%= form_for @language do |f| %>
  <p>
    <%= f.label :name_of_language %>
    <%= f.text_field :name_of_language %>
  </p>
  <p>
    <%= f.label :country_spoken %>
    <%= f.text_field :country_spoken %>
  </p>
  <p>
    <%= f.submit 'Create language' %>
  </p>
<% end %>

<% @languages.each do |language| %>
<ul>
  <li>
    <%= language.name_of_language %>, <%= language.country_spoken %>
  </li>
</ul>
<% end %>

app/views/languages/show.html.erb
<ul>
  <li>
   <%= @language.name_of_language %>, <%= @language.country_spoken %>
  </li>
</ul>

<%= link_to 'Edit language', edit_language_path(@language) %><br>
<%= link_to 'Delete language', language_path(@language), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudLanguages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add a language', languages_path %>